/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarContent: typeof import('./components/calendar/CalendarContent.vue')['default']
    CalendarCreateEventModal: typeof import('./components/calendar/CalendarCreateEventModal.vue')['default']
    CalendarFooter: typeof import('./components/calendar/CalendarFooter.vue')['default']
    CalendarHeader: typeof import('./components/calendar/CalendarHeader.vue')['default']
    copy: typeof import('./components/settings/SettingsLogoSection copy.vue')['default']
    FullScreenLoader: typeof import('./components/common/FullScreenLoader.vue')['default']
    ModalsResolver: typeof import('./components/modals/ModalsResolver.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsEventSection: typeof import('./components/settings/SettingsEventSection.vue')['default']
    SettingsHeader: typeof import('./components/settings/SettingsHeader.vue')['default']
    SettingsLogoSection: typeof import('./components/settings/SettingsLogoSection.vue')['default']
    SettingsQuillEditorModal: typeof import('./components/settings/SettingsQuillEditorModal.vue')['default']
    Toast: typeof import('./components/common/Toast.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
